name: ci
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install cpplint
        run: |
          wget https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
          sudo cp cpplint.py /usr/bin
          sudo chmod +x /usr/bin/cpplint.py

      - uses: actions/setup-python@v4
        with:
          python-version: '2.7'
          architecture: 'x64'

      - name: Check code in /src
        run: find src/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py
      - name: Check code in /tests
        run: find tests/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py

  build:
    runs-on: ubuntu-22.04
    needs: cpplint
    steps:
      - uses: actions/checkout@v2
      - name: Install conan
        run: pip3 install conan
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
      - uses: actions/upload-artifact@master
        with:
          name: package
          path: ./build

  unit_tests:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: package
          path: ./build
      - name: Make executable
        run: chmod +x ./build/bin/unit_tests
      - name: Run tests
        run: ./build/bin/unit_tests


  sanity_tests:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: package
          path: ./build
      - name: Make executable
        run: chmod +x ./build/bin/reduct-cli
      - name: Run tests
        run: ./build/bin/reduct-cli --version