name: ci
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cpplint
        run: | 
          wget https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
          cp cpplint.py /usr/bin
          chmod +x /usr/bin/cpplint.py

      - name: Check code in /src
        run: docker run -v ${PWD}:/app cpplint bash -c "find src/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"
      - name: Check code in /tests
        run: docker run -v ${PWD}:/app cpplint bash -c "find tests/ -name "*.cc" -o -name "*.h"  | xargs cpplint.py"

  build:
    runs-on: ubuntu-latest
    needs: cpplint
    steps:
      - uses: actions/checkout@v2
      - name: Install conan
        run: pip3 install conan
      - name: Build
        run:  |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
      - uses: actions/upload-artifact@master
        with:
          name: package
          path: ./build

  unit_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: package
          path: ./build

      - name: Run tests
        run: ./build/test/unit_tests


  sanity_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: package
          path: ./build

      - name: Run tests
        run: ./build/test/reduct-cli --help